environment:
  SPACES_ENDPOINT: "${SPACES_ENDPOINT}"
  SPACES_NAME: "${SPACES_NAME}"
  SPACES_KEY: "${SPACES_KEY}"
  SPACES_SECRET: "${SPACES_SECRET}"
  PUBLIC_URL: "${PUBLIC_URL}"
  APP_URL: "${APP_URL}"
  APP_DOMAIN: "${APP_DOMAIN}"